### ISSUE TITLE
Importer not available for the new version of Anki

### ISSUE THREAD

**Issue by ghost** [TentativeConvert/LaTeX-Note-Importer-for-Anki#6]
Tried to find some Anki version reference for the note importer add-on, but couldn't find it. I'm using Anki version 2.1.0beta16.

The importer has been working nicely so far and I've used it a lot. Latest update apparently broke the compatibility. Please verify the version it works for and maybe, if you have time, check what are the next changes to make the importer add-on available for the newest Anki versions so if I or someone else has time and the inclination, they could contribute.

Thanks for this nice helper for Anki!

**Comment by TentativeConvert** [comment]
Recently, the title of the [page on which this add-on is listed](https://ankiweb.net/shared/addons/) has changed from *Add-ons for Anki* to *Add-ons for Anki 2.0*.  It seems that the update to Anki 2.1 will require changes in most add-ons. 

There are some instructions on updating add-ons to 2.1 in the section [*Porting Anki 2.0 add-ons*](https://apps.ankiweb.net/docs/addons21.html#porting-anki-2.0-add-ons) in the Anki docs.  I haven't yet looked at these in detail.  If you already have Anki 2.1 beta installed to play around with it, any contribution would be appreciated.  Otherwise, I will probably wait for a stable version before attempting to migrate.

**Comment by ghost** [comment]
Thanks! I'll see what I can do about it.

**Comment by TentativeConvert** [comment]
The addon is now available for Anki 2.1.
